name: Manage Package Versions

on:
  push:
    branches:
      - main

jobs:

  manage_versions:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set package versions
        env:
          PACKAGE_A_VERSION: v1.0.0
          # PACKAGE_B_VERSION: v1.0.0
          # PACKAGE_C_VERSION: v1.0.0
          # PACKAGE_D_VERSION: v1.0.0
        # run: |
        #   # Update package versions based on changes
        #   # For example, increment versions if a change is detected

      - name: Update package version tags
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          git config --local user.email "chavit@skyvar.co.il"
          git config --local user.name "ChaviTynkielrot"
          git tag $PACKAGE_A_VERSION -f
        # git tag $PACKAGE_B_VERSION -f
        # git tag $PACKAGE_C_VERSION -f
        # git tag $PACKAGE_D_VERSION -f
          git push origin $PACKAGE_A_VERSION -f
        # git push origin $PACKAGE_B_VERSION -f
        # git push origin $PACKAGE_C_VERSION -f
        # git push origin $PACKAGE_D_VERSION -f

      # - name: Create repository release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     latest_tag=$(git describe --abbrev=0 --tags)
      #     new_tag=$(echo $latest_tag | awk -F '.' '{print $1 "." $2 "." $3+1}')
      #     git tag $new_tag
      #     git push origin $new_tag